In [5]:
# create two python lists:
list_1 = list(range(1000))
list_2 = list(range(2000, 3000))
list_2

[2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 2025,
 2026,
 2027,
 2028,
 2029,
 2030,
 2031,
 2032,
 2033,
 2034,
 2035,
 2036,
 2037,
 2038,
 2039,
 2040,
 2041,
 2042,
 2043,
 2044,
 2045,
 2046,
 2047,
 2048,
 2049,
 2050,
 2051,
 2052,
 2053,
 2054,
 2055,
 2056,
 2057,
 2058,
 2059,
 2060,
 2061,
 2062,
 2063,
 2064,
 2065,
 2066,
 2067,
 2068,
 2069,
 2070,
 2071,
 2072,
 2073,
 2074,
 2075,
 2076,
 2077,
 2078,
 2079,
 2080,
 2081,
 2082,
 2083,
 2084,
 2085,
 2086,
 2087,
 2088,
 2089,
 2090,
 2091,
 2092,
 2093,
 2094,
 2095,
 2096,
 2097,
 2098,
 2099,
 2100,
 2101,
 2102,
 2103,
 2104,
 2105,
 2106,
 2107,
 2108,
 2109,
 2110,
 2111,
 2112,
 2113,
 2114,
 2115,
 2116,
 2117,
 2118,
 2119,
 2120,
 2121,
 2122,
 2123,
 2124,
 2125,
 2126,
 2127,
 2128,
 2129,
 2130,
 2131,
 2132,
 2133,
 2134,
 2135,
 2136,
 2137,
 2138,
 2139,
 2140,
 2141,
 2142,
 2143,
 2144,
 2145,
 2146,
 2147,
 2148,
 2149,
 2150,
 2151,
 2152,
 2153,
 2154,
 2155,
 2156,
 2157,
 2158,
 2159,
 2160,
 2161,
 2162,
 2163,
 2164,
 2165,
 2166,
 2167,
 2168,
 2169,
 2170,
 2171,
 2172,
 2173,
 2174,
 2175,
 2176,
 2177,
 2178,
 2179,
 2180,
 2181,
 2182,
 2183,
 2184,
 2185,
 2186,
 2187,
 2188,
 2189,
 2190,
 2191,
 2192,
 2193,
 2194,
 2195,
 2196,
 2197,
 2198,
 2199,
 2200,
 2201,
 2202,
 2203,
 2204,
 2205,
 2206,
 2207,
 2208,
 2209,
 2210,
 2211,
 2212,
 2213,
 2214,
 2215,
 2216,
 2217,
 2218,
 2219,
 2220,
 2221,
 2222,
 2223,
 2224,
 2225,
 2226,
 2227,
 2228,
 2229,
 2230,
 2231,
 2232,
 2233,
 2234,
 2235,
 2236,
 2237,
 2238,
 2239,
 2240,
 2241,
 2242,
 2243,
 2244,
 2245,
 2246,
 2247,
 2248,
 2249,
 2250,
 2251,
 2252,
 2253,
 2254,
 2255,
 2256,
 2257,
 2258,
 2259,
 2260,
 2261,
 2262,
 2263,
 2264,
 2265,
 2266,
 2267,
 2268,
 2269,
 2270,
 2271,
 2272,
 2273,
 2274,
 2275,
 2276,
 2277,
 2278,
 2279,
 2280,
 2281,
 2282,
 2283,
 2284,
 2285,
 2286,
 2287,
 2288,
 2289,
 2290,
 2291,
 2292,
 2293,
 2294,
 2295,
 2296,
 2297,
 2298,
 2299,
 2300,
 2301,
 2302,
 2303,
 2304,
 2305,
 2306,
 2307,
 2308,
 2309,
 2310,
 2311,
 2312,
 2313,
 2314,
 2315,
 2316,
 2317,
 2318,
 2319,
 2320,
 2321,
 2322,
 2323,
 2324,
 2325,
 2326,
 2327,
 2328,
 2329,
 2330,
 2331,
 2332,
 2333,
 2334,
 2335,
 2336,
 2337,
 2338,
 2339,
 2340,
 2341,
 2342,
 2343,
 2344,
 2345,
 2346,
 2347,
 2348,
 2349,
 2350,
 2351,
 2352,
 2353,
 2354,
 2355,
 2356,
 2357,
 2358,
 2359,
 2360,
 2361,
 2362,
 2363,
 2364,
 2365,
 2366,
 2367,
 2368,
 2369,
 2370,
 2371,
 2372,
 2373,
 2374,
 2375,
 2376,
 2377,
 2378,
 2379,
 2380,
 2381,
 2382,
 2383,
 2384,
 2385,
 2386,
 2387,
 2388,
 2389,
 2390,
 2391,
 2392,
 2393,
 2394,
 2395,
 2396,
 2397,
 2398,
 2399,
 2400,
 2401,
 2402,
 2403,
 2404,
 2405,
 2406,
 2407,
 2408,
 2409,
 2410,
 2411,
 2412,
 2413,
 2414,
 2415,
 2416,
 2417,
 2418,
 2419,
 2420,
 2421,
 2422,
 2423,
 2424,
 2425,
 2426,
 2427,
 2428,
 2429,
 2430,
 2431,
 2432,
 2433,
 2434,
 2435,
 2436,
 2437,
 2438,
 2439,
 2440,
 2441,
 2442,
 2443,
 2444,
 2445,
 2446,
 2447,
 2448,
 2449,
 2450,
 2451,
 2452,
 2453,
 2454,
 2455,
 2456,
 2457,
 2458,
 2459,
 2460,
 2461,
 2462,
 2463,
 2464,
 2465,
 2466,
 2467,
 2468,
 2469,
 2470,
 2471,
 2472,
 2473,
 2474,
 2475,
 2476,
 2477,
 2478,
 2479,
 2480,
 2481,
 2482,
 2483,
 2484,
 2485,
 2486,
 2487,
 2488,
 2489,
 2490,
 2491,
 2492,
 2493,
 2494,
 2495,
 2496,
 2497,
 2498,
 2499,
 2500,
 2501,
 2502,
 2503,
 2504,
 2505,
 2506,
 2507,
 2508,
 2509,
 2510,
 2511,
 2512,
 2513,
 2514,
 2515,
 2516,
 2517,
 2518,
 2519,
 2520,
 2521,
 2522,
 2523,
 2524,
 2525,
 2526,
 2527,
 2528,
 2529,
 2530,
 2531,
 2532,
 2533,
 2534,
 2535,
 2536,
 2537,
 2538,
 2539,
 2540,
 2541,
 2542,
 2543,
 2544,
 2545,
 2546,
 2547,
 2548,
 2549,
 2550,
 2551,
 2552,
 2553,
 2554,
 2555,
 2556,
 2557,
 2558,
 2559,
 2560,
 2561,
 2562,
 2563,
 2564,
 2565,
 2566,
 2567,
 2568,
 2569,
 2570,
 2571,
 2572,
 2573,
 2574,
 2575,
 2576,
 2577,
 2578,
 2579,
 2580,
 2581,
 2582,
 2583,
 2584,
 2585,
 2586,
 2587,
 2588,
 2589,
 2590,
 2591,
 2592,
 2593,
 2594,
 2595,
 2596,
 2597,
 2598,
 2599,
 2600,
 2601,
 2602,
 2603,
 2604,
 2605,
 2606,
 2607,
 2608,
 2609,
 2610,
 2611,
 2612,
 2613,
 2614,
 2615,
 2616,
 2617,
 2618,
 2619,
 2620,
 2621,
 2622,
 2623,
 2624,
 2625,
 2626,
 2627,
 2628,
 2629,
 2630,
 2631,
 2632,
 2633,
 2634,
 2635,
 2636,
 2637,
 2638,
 2639,
 2640,
 2641,
 2642,
 2643,
 2644,
 2645,
 2646,
 2647,
 2648,
 2649,
 2650,
 2651,
 2652,
 2653,
 2654,
 2655,
 2656,
 2657,
 2658,
 2659,
 2660,
 2661,
 2662,
 2663,
 2664,
 2665,
 2666,
 2667,
 2668,
 2669,
 2670,
 2671,
 2672,
 2673,
 2674,
 2675,
 2676,
 2677,
 2678,
 2679,
 2680,
 2681,
 2682,
 2683,
 2684,
 2685,
 2686,
 2687,
 2688,
 2689,
 2690,
 2691,
 2692,
 2693,
 2694,
 2695,
 2696,
 2697,
 2698,
 2699,
 2700,
 2701,
 2702,
 2703,
 2704,
 2705,
 2706,
 2707,
 2708,
 2709,
 2710,
 2711,
 2712,
 2713,
 2714,
 2715,
 2716,
 2717,
 2718,
 2719,
 2720,
 2721,
 2722,
 2723,
 2724,
 2725,
 2726,
 2727,
 2728,
 2729,
 2730,
 2731,
 2732,
 2733,
 2734,
 2735,
 2736,
 2737,
 2738,
 2739,
 2740,
 2741,
 2742,
 2743,
 2744,
 2745,
 2746,
 2747,
 2748,
 2749,
 2750,
 2751,
 2752,
 2753,
 2754,
 2755,
 2756,
 2757,
 2758,
 2759,
 2760,
 2761,
 2762,
 2763,
 2764,
 2765,
 2766,
 2767,
 2768,
 2769,
 2770,
 2771,
 2772,
 2773,
 2774,
 2775,
 2776,
 2777,
 2778,
 2779,
 2780,
 2781,
 2782,
 2783,
 2784,
 2785,
 2786,
 2787,
 2788,
 2789,
 2790,
 2791,
 2792,
 2793,
 2794,
 2795,
 2796,
 2797,
 2798,
 2799,
 2800,
 2801,
 2802,
 2803,
 2804,
 2805,
 2806,
 2807,
 2808,
 2809,
 2810,
 2811,
 2812,
 2813,
 2814,
 2815,
 2816,
 2817,
 2818,
 2819,
 2820,
 2821,
 2822,
 2823,
 2824,
 2825,
 2826,
 2827,
 2828,
 2829,
 2830,
 2831,
 2832,
 2833,
 2834,
 2835,
 2836,
 2837,
 2838,
 2839,
 2840,
 2841,
 2842,
 2843,
 2844,
 2845,
 2846,
 2847,
 2848,
 2849,
 2850,
 2851,
 2852,
 2853,
 2854,
 2855,
 2856,
 2857,
 2858,
 2859,
 2860,
 2861,
 2862,
 2863,
 2864,
 2865,
 2866,
 2867,
 2868,
 2869,
 2870,
 2871,
 2872,
 2873,
 2874,
 2875,
 2876,
 2877,
 2878,
 2879,
 2880,
 2881,
 2882,
 2883,
 2884,
 2885,
 2886,
 2887,
 2888,
 2889,
 2890,
 2891,
 2892,
 2893,
 2894,
 2895,
 2896,
 2897,
 2898,
 2899,
 2900,
 2901,
 2902,
 2903,
 2904,
 2905,
 2906,
 2907,
 2908,
 2909,
 2910,
 2911,
 2912,
 2913,
 2914,
 2915,
 2916,
 2917,
 2918,
 2919,
 2920,
 2921,
 2922,
 2923,
 2924,
 2925,
 2926,
 2927,
 2928,
 2929,
 2930,
 2931,
 2932,
 2933,
 2934,
 2935,
 2936,
 2937,
 2938,
 2939,
 2940,
 2941,
 2942,
 2943,
 2944,
 2945,
 2946,
 2947,
 2948,
 2949,
 2950,
 2951,
 2952,
 2953,
 2954,
 2955,
 2956,
 2957,
 2958,
 2959,
 2960,
 2961,
 2962,
 2963,
 2964,
 2965,
 2966,
 2967,
 2968,
 2969,
 2970,
 2971,
 2972,
 2973,
 2974,
 2975,
 2976,
 2977,
 2978,
 2979,
 2980,
 2981,
 2982,
 2983,
 2984,
 2985,
 2986,
 2987,
 2988,
 2989,
 2990,
 2991,
 2992,
 2993,
 2994,
 2995,
 2996,
 2997,
 2998,
 2999]

Import NumPy and Create two numpy arrays using the two Python lists:

In [6]:
import  numpy as np

In [7]:
arr_1 = np.array(list_1)
arr_2 = np.array(list_2)

In [8]:
arr_1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

Define a function that will perform element wise addition of two Python lists.

In [9]:
def list_sum(l,l2):
    new_list = []
    for item in range(len(l)):
        new_list.append(l[item] + l2[item])
    return new_list

In [10]:
lst = list_sum(list_1, list_2)

Define a function that will perform element wise addition of two NumPy arrays.

In [11]:
# def array_sum(a, b):
#     new_array = []
#     for item in a:
#         new_array.append(a[item] + b[item])
#     return new_array

In [12]:
def array_sum():
    return arr_1 + arr_2

In [13]:
array_sum()

array([2000, 2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018, 2020,
       2022, 2024, 2026, 2028, 2030, 2032, 2034, 2036, 2038, 2040, 2042,
       2044, 2046, 2048, 2050, 2052, 2054, 2056, 2058, 2060, 2062, 2064,
       2066, 2068, 2070, 2072, 2074, 2076, 2078, 2080, 2082, 2084, 2086,
       2088, 2090, 2092, 2094, 2096, 2098, 2100, 2102, 2104, 2106, 2108,
       2110, 2112, 2114, 2116, 2118, 2120, 2122, 2124, 2126, 2128, 2130,
       2132, 2134, 2136, 2138, 2140, 2142, 2144, 2146, 2148, 2150, 2152,
       2154, 2156, 2158, 2160, 2162, 2164, 2166, 2168, 2170, 2172, 2174,
       2176, 2178, 2180, 2182, 2184, 2186, 2188, 2190, 2192, 2194, 2196,
       2198, 2200, 2202, 2204, 2206, 2208, 2210, 2212, 2214, 2216, 2218,
       2220, 2222, 2224, 2226, 2228, 2230, 2232, 2234, 2236, 2238, 2240,
       2242, 2244, 2246, 2248, 2250, 2252, 2254, 2256, 2258, 2260, 2262,
       2264, 2266, 2268, 2270, 2272, 2274, 2276, 2278, 2280, 2282, 2284,
       2286, 2288, 2290, 2292, 2294, 2296, 2298, 2300, 2302, 2304, 2306,
       2308, 2310, 2312, 2314, 2316, 2318, 2320, 2322, 2324, 2326, 2328,
       2330, 2332, 2334, 2336, 2338, 2340, 2342, 2344, 2346, 2348, 2350,
       2352, 2354, 2356, 2358, 2360, 2362, 2364, 2366, 2368, 2370, 2372,
       2374, 2376, 2378, 2380, 2382, 2384, 2386, 2388, 2390, 2392, 2394,
       2396, 2398, 2400, 2402, 2404, 2406, 2408, 2410, 2412, 2414, 2416,
       2418, 2420, 2422, 2424, 2426, 2428, 2430, 2432, 2434, 2436, 2438,
       2440, 2442, 2444, 2446, 2448, 2450, 2452, 2454, 2456, 2458, 2460,
       2462, 2464, 2466, 2468, 2470, 2472, 2474, 2476, 2478, 2480, 2482,
       2484, 2486, 2488, 2490, 2492, 2494, 2496, 2498, 2500, 2502, 2504,
       2506, 2508, 2510, 2512, 2514, 2516, 2518, 2520, 2522, 2524, 2526,
       2528, 2530, 2532, 2534, 2536, 2538, 2540, 2542, 2544, 2546, 2548,
       2550, 2552, 2554, 2556, 2558, 2560, 2562, 2564, 2566, 2568, 2570,
       2572, 2574, 2576, 2578, 2580, 2582, 2584, 2586, 2588, 2590, 2592,
       2594, 2596, 2598, 2600, 2602, 2604, 2606, 2608, 2610, 2612, 2614,
       2616, 2618, 2620, 2622, 2624, 2626, 2628, 2630, 2632, 2634, 2636,
       2638, 2640, 2642, 2644, 2646, 2648, 2650, 2652, 2654, 2656, 2658,
       2660, 2662, 2664, 2666, 2668, 2670, 2672, 2674, 2676, 2678, 2680,
       2682, 2684, 2686, 2688, 2690, 2692, 2694, 2696, 2698, 2700, 2702,
       2704, 2706, 2708, 2710, 2712, 2714, 2716, 2718, 2720, 2722, 2724,
       2726, 2728, 2730, 2732, 2734, 2736, 2738, 2740, 2742, 2744, 2746,
       2748, 2750, 2752, 2754, 2756, 2758, 2760, 2762, 2764, 2766, 2768,
       2770, 2772, 2774, 2776, 2778, 2780, 2782, 2784, 2786, 2788, 2790,
       2792, 2794, 2796, 2798, 2800, 2802, 2804, 2806, 2808, 2810, 2812,
       2814, 2816, 2818, 2820, 2822, 2824, 2826, 2828, 2830, 2832, 2834,
       2836, 2838, 2840, 2842, 2844, 2846, 2848, 2850, 2852, 2854, 2856,
       2858, 2860, 2862, 2864, 2866, 2868, 2870, 2872, 2874, 2876, 2878,
       2880, 2882, 2884, 2886, 2888, 2890, 2892, 2894, 2896, 2898, 2900,
       2902, 2904, 2906, 2908, 2910, 2912, 2914, 2916, 2918, 2920, 2922,
       2924, 2926, 2928, 2930, 2932, 2934, 2936, 2938, 2940, 2942, 2944,
       2946, 2948, 2950, 2952, 2954, 2956, 2958, 2960, 2962, 2964, 2966,
       2968, 2970, 2972, 2974, 2976, 2978, 2980, 2982, 2984, 2986, 2988,
       2990, 2992, 2994, 2996, 2998, 3000, 3002, 3004, 3006, 3008, 3010,
       3012, 3014, 3016, 3018, 3020, 3022, 3024, 3026, 3028, 3030, 3032,
       3034, 3036, 3038, 3040, 3042, 3044, 3046, 3048, 3050, 3052, 3054,
       3056, 3058, 3060, 3062, 3064, 3066, 3068, 3070, 3072, 3074, 3076,
       3078, 3080, 3082, 3084, 3086, 3088, 3090, 3092, 3094, 3096, 3098,
       3100, 3102, 3104, 3106, 3108, 3110, 3112, 3114, 3116, 3118, 3120,
       3122, 3124, 3126, 3128, 3130, 3132, 3134, 3136, 3138, 3140, 3142,
       3144, 3146, 3148, 3150, 3152, 3154, 3156, 3158, 3160, 3162, 3164,
       3166, 3168, 3170, 3172, 3174, 3176, 3178, 3180, 3182, 3184, 3186,
       3188, 3190, 3192, 3194, 3196, 3198, 3200, 3202, 3204, 3206, 3208,
       3210, 3212, 3214, 3216, 3218, 3220, 3222, 3224, 3226, 3228, 3230,
       3232, 3234, 3236, 3238, 3240, 3242, 3244, 3246, 3248, 3250, 3252,
       3254, 3256, 3258, 3260, 3262, 3264, 3266, 3268, 3270, 3272, 3274,
       3276, 3278, 3280, 3282, 3284, 3286, 3288, 3290, 3292, 3294, 3296,
       3298, 3300, 3302, 3304, 3306, 3308, 3310, 3312, 3314, 3316, 3318,
       3320, 3322, 3324, 3326, 3328, 3330, 3332, 3334, 3336, 3338, 3340,
       3342, 3344, 3346, 3348, 3350, 3352, 3354, 3356, 3358, 3360, 3362,
       3364, 3366, 3368, 3370, 3372, 3374, 3376, 3378, 3380, 3382, 3384,
       3386, 3388, 3390, 3392, 3394, 3396, 3398, 3400, 3402, 3404, 3406,
       3408, 3410, 3412, 3414, 3416, 3418, 3420, 3422, 3424, 3426, 3428,
       3430, 3432, 3434, 3436, 3438, 3440, 3442, 3444, 3446, 3448, 3450,
       3452, 3454, 3456, 3458, 3460, 3462, 3464, 3466, 3468, 3470, 3472,
       3474, 3476, 3478, 3480, 3482, 3484, 3486, 3488, 3490, 3492, 3494,
       3496, 3498, 3500, 3502, 3504, 3506, 3508, 3510, 3512, 3514, 3516,
       3518, 3520, 3522, 3524, 3526, 3528, 3530, 3532, 3534, 3536, 3538,
       3540, 3542, 3544, 3546, 3548, 3550, 3552, 3554, 3556, 3558, 3560,
       3562, 3564, 3566, 3568, 3570, 3572, 3574, 3576, 3578, 3580, 3582,
       3584, 3586, 3588, 3590, 3592, 3594, 3596, 3598, 3600, 3602, 3604,
       3606, 3608, 3610, 3612, 3614, 3616, 3618, 3620, 3622, 3624, 3626,
       3628, 3630, 3632, 3634, 3636, 3638, 3640, 3642, 3644, 3646, 3648,
       3650, 3652, 3654, 3656, 3658, 3660, 3662, 3664, 3666, 3668, 3670,
       3672, 3674, 3676, 3678, 3680, 3682, 3684, 3686, 3688, 3690, 3692,
       3694, 3696, 3698, 3700, 3702, 3704, 3706, 3708, 3710, 3712, 3714,
       3716, 3718, 3720, 3722, 3724, 3726, 3728, 3730, 3732, 3734, 3736,
       3738, 3740, 3742, 3744, 3746, 3748, 3750, 3752, 3754, 3756, 3758,
       3760, 3762, 3764, 3766, 3768, 3770, 3772, 3774, 3776, 3778, 3780,
       3782, 3784, 3786, 3788, 3790, 3792, 3794, 3796, 3798, 3800, 3802,
       3804, 3806, 3808, 3810, 3812, 3814, 3816, 3818, 3820, 3822, 3824,
       3826, 3828, 3830, 3832, 3834, 3836, 3838, 3840, 3842, 3844, 3846,
       3848, 3850, 3852, 3854, 3856, 3858, 3860, 3862, 3864, 3866, 3868,
       3870, 3872, 3874, 3876, 3878, 3880, 3882, 3884, 3886, 3888, 3890,
       3892, 3894, 3896, 3898, 3900, 3902, 3904, 3906, 3908, 3910, 3912,
       3914, 3916, 3918, 3920, 3922, 3924, 3926, 3928, 3930, 3932, 3934,
       3936, 3938, 3940, 3942, 3944, 3946, 3948, 3950, 3952, 3954, 3956,
       3958, 3960, 3962, 3964, 3966, 3968, 3970, 3972, 3974, 3976, 3978,
       3980, 3982, 3984, 3986, 3988, 3990, 3992, 3994, 3996, 3998])

Notice the time taken by both the functions: list and array

In [14]:
# import timer from timeit library
from timeit import Timer

In [15]:
timer_1 = Timer("lst",
                "from __main__ import lst")

In [16]:
print("Pure python: ", timer_1.timeit(1000))

Pure python:  1.409999999779643e-05

In [17]:
timer_2 = Timer("array_sum()",
                "from __main__ import array_sum")

In [18]:
print("Numpy version: ", timer_2.timeit(1000))

Numpy version:  0.0023484000000024707

## observation:
- Numpy is significantly faster than Python

In [19]:
lst_new = np.arange(2, 13, 2)

In [20]:
lst_new

array([ 2,  4,  6,  8, 10, 12])

In [21]:
arr = np.array([
    [1,2,4],
    [8,45,34],
    [34,36,67]
])

In [22]:
arr

array([[ 1,  2,  4],
       [ 8, 45, 34],
       [34, 36, 67]])

In [23]:
array_1 = np.arange(10)

In [24]:
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# The zeros() function creates an n-dimensional array of zeros.
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
# linspace () generates values which are equally spaced from each other
arr_new = np.linspace(start=10, stop=40, num=40)

In [28]:
arr_new

array([10.        , 10.76923077, 11.53846154, 12.30769231, 13.07692308,
       13.84615385, 14.61538462, 15.38461538, 16.15384615, 16.92307692,
       17.69230769, 18.46153846, 19.23076923, 20.        , 20.76923077,
       21.53846154, 22.30769231, 23.07692308, 23.84615385, 24.61538462,
       25.38461538, 26.15384615, 26.92307692, 27.69230769, 28.46153846,
       29.23076923, 30.        , 30.76923077, 31.53846154, 32.30769231,
       33.07692308, 33.84615385, 34.61538462, 35.38461538, 36.15384615,
       36.92307692, 37.69230769, 38.46153846, 39.23076923, 40.        ])

In [29]:
# Write a Python program to create a NumPy array based on the following list:
list = [2, 5, 8, 6, 4, 12, 16, 15]
new_array = np.array(list)
new_array

array([ 2,  5,  8,  6,  4, 12, 16, 15])

In [30]:
new_array.shape

(8,)

In [31]:
new_array.ndim

1

Write a Python program to create an array of elements as per the below condition.
- The array must start with 17
- The array must end at 31
- The values in the array must be equally spaced or linearly spaced
- The array should have 50 samples/values in it.

In [32]:
np.linspace(start=17,stop=31, num=50)

array([17.        , 17.28571429, 17.57142857, 17.85714286, 18.14285714,
       18.42857143, 18.71428571, 19.        , 19.28571429, 19.57142857,
       19.85714286, 20.14285714, 20.42857143, 20.71428571, 21.        ,
       21.28571429, 21.57142857, 21.85714286, 22.14285714, 22.42857143,
       22.71428571, 23.        , 23.28571429, 23.57142857, 23.85714286,
       24.14285714, 24.42857143, 24.71428571, 25.        , 25.28571429,
       25.57142857, 25.85714286, 26.14285714, 26.42857143, 26.71428571,
       27.        , 27.28571429, 27.57142857, 27.85714286, 28.14285714,
       28.42857143, 28.71428571, 29.        , 29.28571429, 29.57142857,
       29.85714286, 30.14285714, 30.42857143, 30.71428571, 31.        ])

In [33]:
# a list of programming languages
['Python', 'C++', 'JavaScript']

['Python', 'C++', 'JavaScript']

In [34]:
# list of integers
my_list = [1, 2, 3]

In [35]:
# empty list
lst = []

In [36]:
# list with mixed data types
my_list = [9, "Espanol", 4.6, ['a','b','c']]
my_list

[9, 'Espanol', 4.6, ['a', 'b', 'c']]

In [37]:
# nested list
nested_list = ["mouse", [8, 4, 6], ['a'], ['joy', 'deb']]

In [38]:
nested_list

['mouse', [8, 4, 6], ['a'], ['joy', 'deb']]

# Arrays
- Similar to a list, an array is also a data structure which can hold more than one value at a time
- However, an array can only hold a collection of ordered elements of the same data type.

In [39]:
heights = [165, 170, 171, 180, 189, 178]
print(type(heights))

heights_np = np.array(heights)
print(type(heights_np))

<class 'list'>
<class 'numpy.ndarray'>

In [40]:
weights = np.array([[50, 45, 56, 78],
                    [78, 89, 59, 90],
                    [89, 78, 69, 70],
                    [67, 69, 89, 70],
                    [90,89, 80, 84],
                    [89, 59, 90, 78]]
                   )
print(weights)

[[50 45 56 78]
 [78 89 59 90]
 [89 78 69 70]
 [67 69 89 70]
 [90 89 80 84]
 [89 59 90 78]]

In [41]:
weights.ndim  # it is a dimensional array

2

In [42]:
weights.shape   # it has 6 rows and 4 columns

(6, 4)

In [43]:
weights.size  # it has 24 elements

24

In [44]:
weights.dtype    # int32 dtypes because each element of the array is a 32-bit (4-byte) integer

dtype('int32')

In [45]:
weights.strides

(16, 4)

strides of (16, 4) since 16 bytes (4 integers of 4 bytes in the rows) are needed to store each row in memory and 4 bytes (1 integer per column) to store each column in memory.

In [46]:
a  = np.array(42)
a.ndim

0

In [47]:
b = np.array([1, 2, 3, 4, 5])
b.ndim

1

In [48]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c.ndim

2

In [49]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [50]:
# zeros(shape=(n,m)) : Allows to create a zero-array with the shape (n rows, m columns)
x = np.zeros(shape=(5,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
# full(shape=(n,m), fill_value=f): Allows to create an array with the shape (n rows,m columns), where all positions have the value f.?

np.full(shape=(6,4),fill_value=6, dtype=complex)   ## Creating an array of complex type having constant values

array([[6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j]])

In [52]:
np.full(shape=(6,4),fill_value=6, dtype='int32')

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [53]:
# Create an array with random values
np.random.randint(4,100, size=34)

array([27, 34, 41, 32, 19, 95, 55, 35, 70, 75, 10, 57, 26, 37, 12, 57, 62,
       73, 71, 78,  9, 70, 35, 12, 72, 80, 67, 98, 32, 83, 78, 24, 28, 85])

In [54]:
np.random.random((4,6))

array([[0.30297897, 0.84918159, 0.00497463, 0.35299137, 0.92466249,
        0.93826398],
       [0.86705403, 0.89031139, 0.39309698, 0.48613574, 0.34762874,
        0.60105226],
       [0.85643762, 0.02677233, 0.98305192, 0.44867214, 0.77093804,
        0.53005415],
       [0.91711423, 0.34602487, 0.89719048, 0.44911143, 0.49073982,
        0.7475805 ]])

In [55]:
np.arange(100, 15000,1000)

array([  100,  1100,  2100,  3100,  4100,  5100,  6100,  7100,  8100,
        9100, 10100, 11100, 12100, 13100, 14100])

In [56]:
# Create a sequence of 10 values in range 0 to 5
np.linspace(0,5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [57]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[50, 45, 56, 78],[78, 89, 59, 90],[89, 78, 69, 70],[67, 69, 89, 70],[90,89, 80, 84],[89, 59, 90, 78]])
arr

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [58]:
new_arr = arr.reshape(2,6,2)

In [59]:
new_arr

array([[[50, 45],
        [56, 78],
        [78, 89],
        [59, 90],
        [89, 78],
        [69, 70]],

       [[67, 69],
        [89, 70],
        [90, 89],
        [80, 84],
        [89, 59],
        [90, 78]]])

In [60]:
# flatten array
arr

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [61]:
arr.flatten()

array([50, 45, 56, 78, 78, 89, 59, 90, 89, 78, 69, 70, 67, 69, 89, 70, 90,
       89, 80, 84, 89, 59, 90, 78])

In [62]:
# appending an element in to the array
np.append(new_arr, 14)

array([50, 45, 56, 78, 78, 89, 59, 90, 89, 78, 69, 70, 67, 69, 89, 70, 90,
       89, 80, 84, 89, 59, 90, 78, 14])

In [63]:
lst = [1,3,5,6,7,8]
np.append(new_arr, lst)     # it is possible to append python list to numpy array

array([50, 45, 56, 78, 78, 89, 59, 90, 89, 78, 69, 70, 67, 69, 89, 70, 90,
       89, 80, 84, 89, 59, 90, 78,  1,  3,  5,  6,  7,  8])

In [64]:
# append method directly doesnt work on the array    unlike list
new_arr.append(5)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
np.delete(new_arr, 13)

In [ ]:
sorted_array = np.sort(new_arr)

In [ ]:
sorted_array

In [ ]:
arr = np.arange(24)
arr

In [ ]:
np.reshape(arr, (3,4,2))

In [ ]:
arr.reshape(6,4)

In [ ]:
# Create a NumPy array (there must be first 16 numbers starting from 0 to 16 (exclusive)) using a function arange(). Select the correct array.
np.arange(17)

In [68]:
# Consider the given Python list and follow the steps below:

L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]

In [74]:
np_arr = np.array(L)     # convert to np array
np_arr#

array([10,  2,  7,  8,  3, 22, 54, 12, 13, 46, 23, 25, 41])

In [79]:
sorted_array =np.sort(np_arr)

In [80]:
sorted_array

array([ 2,  3,  7,  8, 10, 12, 13, 22, 23, 25, 41, 46, 54])

In [81]:
print(sorted_array)

[ 2  3  7  8 10 12 13 22 23 25 41 46 54]

In [84]:
np.delete(np_arr, 4)

array([ 2,  3,  7,  8, 12, 13, 22, 23, 25, 41, 46, 54])

In [85]:
np.append(np_arr, 53)

array([ 2,  3,  7,  8, 10, 12, 13, 22, 23, 25, 41, 46, 54, 53])

In [89]:
np_arr.shape

(13,)

In [90]:
arr

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [93]:
arr[2:5, 1:4]

array([[78, 69, 70],
       [69, 89, 70],
       [89, 80, 84]])

In [96]:
 arr[-4:-1, -3:]

array([[78, 69, 70],
       [69, 89, 70],
       [89, 80, 84]])

In [97]:
# adding 3 to every element
a = np.array([7, 6, 8, 9])
print ("Adding 6 to every element:", a+6)

Adding 1 to every element: [13 12 14 15]

In [98]:
a - 4

array([3, 2, 4, 5])

In [99]:
a * 3

array([21, 18, 24, 27])

In [100]:
a ** 2

array([49, 36, 64, 81], dtype=int32)

In [101]:
a *= 2

In [102]:
a

array([14, 12, 16, 18])

In [103]:
# transpose of array
a = np.array([[3, 1, 2], [6, 5, 4], [7, 9, 8]])

In [104]:
a

array([[3, 1, 2],
       [6, 5, 4],
       [7, 9, 8]])

In [105]:
a.transpose()

array([[3, 6, 7],
       [1, 5, 9],
       [2, 4, 8]])

In [106]:
arr = np.array([1,9,8,4,5,6])
np.append(arr, 77)

array([ 1,  9,  8,  4,  5,  6, 77])

In [107]:
l = [2,3,5,4,7,6]
arr = np.append(l,10)
arr

array([ 2,  3,  5,  4,  7,  6, 10])

In [108]:
np.append(arr, [23,34,55,67])

array([ 2,  3,  5,  4,  7,  6, 10, 23, 34, 55, 67])

In [109]:
# remove an element
np.delete(arr,3)

array([ 2,  3,  5,  7,  6, 10])

In [111]:
# sorting an array of integers
np.sort(arr)

array([ 2,  3,  4,  5,  6,  7, 10])

In [112]:
#sorting an array alphabetically
arr = np.array(['Lamborghini', 'Porsche', 'Mercedes'])
np.sort(arr)

array(['Lamborghini', 'Mercedes', 'Porsche'], dtype='<U11')

In [115]:
#sorting a 2-D array
arr = np.array([
    [5, 7, 8],
    [6, 2, 3]
])
arr

array([[5, 7, 8],
       [6, 2, 3]])

In [116]:
np.sort(arr)

array([[5, 7, 8],
       [2, 3, 6]])

In [117]:
#Find the indexes where the value is 4:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

In [118]:
np.where(arr == 4)

(array([3, 5, 6], dtype=int64),)

In [120]:
np.where(arr % 2 != 0)

(array([0, 2, 4], dtype=int64),)

In [121]:
# Get the first element from the following array:
import numpy as np
arr = np.array([9, 8, 4, 5])

In [122]:
arr[0]

9

In [123]:
arr = np.array([[1,2,3,4,5],
[6,7,8,9,10]])

In [124]:
arr[0][1]

2

In [125]:
arr[0,1]

2

In [126]:
# Slicing elements from index 3 to index 7 in the following array:
arr = np.array([22, 81, 23, 34, 56, 63, 71])

In [127]:
arr[3:7]

array([34, 56, 63, 71])

In [128]:
# Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]

In [129]:
#Slicing 2-D Arrays
# From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

In [132]:
arr[1,1:4]

array([7, 8, 9])

In [133]:
#From both elements, return index 2:
arr = np.array([[1, 2, 4, 5, 3],
                [9, 8, 7, 6, 1]])

In [136]:
arr[:,2]

array([4, 7])

In [137]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [138]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [139]:
arr[:, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [140]:
# Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [141]:
arr[-3:-1]

array([5, 6])

In [143]:
#printing the last two elements
arr = np.array([0, 1, 2, 3, 6, 7, 8, 9])
arr[-2:]

array([8, 9])

In [144]:
arr[-3:3:-1]

array([7, 6])

In [148]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [149]:
np.reshape(arr, (5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])